CREATE TABLE dbo.VendorPricelist(
    [vendorPartId] NVARCHAR(40) NOT NULL CONSTRAINT [DF_VendorPricelist_vendorPartId] DEFAULT (CONVERT(NVARCHAR(40), NEWID())) PRIMARY KEY,
    [vendorId] NVARCHAR(40) NOT NULL,
    [sourceVendorName] NVARCHAR(200) NULL,
    [brand] NVARCHAR(200) NULL,
    [ParentCategory] NVARCHAR(500) NULL,
    [Category] NVARCHAR(500) NULL,
    [PartNumber] NVARCHAR(120) NOT NULL,
    [LongDescription] NVARCHAR(1000) NULL,
    [ServiceDescription] NVARCHAR(1000) NULL,
    [ManufacturerOrReseller] NVARCHAR(500) NULL,
    [MSRPPrice] MONEY NULL,
    [DiscountPercent] DECIMAL(9, 4) NULL,
    [DirAdminFee] MONEY NULL,
    [SalesPrice] MONEY NULL,
    [FuturePrice] MONEY NULL,
    [FutureEffectiveDate] DATE NULL,
    [FutureSalesPrice] MONEY NULL,
    [FutureSalesEffectiveDate] DATE NULL,
    [MinOrderQuantity] INT NULL,
    [ProductStatus] NVARCHAR(500) NULL,
    [Agency] NVARCHAR(50) NULL,
    [CountryOfOrigin] NVARCHAR(50) NULL,
    [UPC] NVARCHAR(50) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [createat] DATETIME NOT NULL CONSTRAINT [DF_VendorPricelist_createat] DEFAULT (GETDATE()),
    [createby] NVARCHAR(40) NOT NULL CONSTRAINT [DF_VendorPricelist_createby] DEFAULT ('system'),
    [updateat] DATETIME NOT NULL CONSTRAINT [DF_VendorPricelist_updateat] DEFAULT (GETDATE()),
    [updateby] NVARCHAR(40) NOT NULL CONSTRAINT [DF_VendorPricelist_updateby] DEFAULT ('system')
)
